### ISSUE TITLE
cdn for font Poiret One isn't available

### ISSUE THREAD

**Issue by StefanYohansson** [moefront/moefront.github.io#5]
the title font Poiret One isn't being downloaded properly.

this address isn't returning: https://cdn.moefont.com/fonts/css?family=Poiret+One

imported here:
`view-source:https://moefront.github.io/moefront.css`

**Comment by kirainmoe** [comment]
I did not notice that font CDN was broken. The broken link has been replaced.
Thanks XD

**Comment by StefanYohansson** [comment]
no problem, I like the site. 🐼
